### ISSUE TITLE
Update project metadata to match repo

### ISSUE THREAD

**Issue by scottyhq** [developmentseed/obstore#100]
This project looks neat! I was going to experiment with the `open()` function but noticed the package metadata is off

https://github.com/developmentseed/obstore/blob/0e48ce2c057ab5cd4f44d7d2816fa01e8802bce2/pyproject.toml#L2-L6

Tools like pixi.sh complain when trying to install from github
>╰─▶ Package metadata name `test-env` does not match given name `obstore`

pip does work, but installs as `test-env` which is confusing: `pip install git+https://github.com/developmentseed/obstore.git@main`
> Successfully installed test-env-0.1.0

**Comment by kylebarron** [comment]
> I was going to experiment with the `open()` function

You can install the latest beta
```
pip install -U --pre obstore
```

> [obstore/pyproject.toml](https://github.com/developmentseed/obstore/blob/0e48ce2c057ab5cd4f44d7d2816fa01e8802bce2/pyproject.toml#L2-L6)

That's the pyproject.toml for the test environment, not the `obstore` library. [This](https://github.com/developmentseed/obstore/blob/0e48ce2c057ab5cd4f44d7d2816fa01e8802bce2/obstore/pyproject.toml) is the one for the obstore library
