### ISSUE TITLE
Feature request: support exclusive put mode

### ISSUE THREAD

**Issue by martindurant** [developmentseed/obstore#73]
This is the "conditional upload" feature, supported by AWS and others for atomic writes, equivalent to "xb" locally. The mode is important, for example, to icechunk, which uses the store atomic operation to ensure there is no race in setting the latest version of a dataset.

cf https://github.com/fsspec/filesystem_spec/issues/1693

**Comment by martindurant** [comment]
On closer reading, I suppose "create" does exactly this - apologies.

**Comment by kylebarron** [comment]
I think so, yes. We should test that it is indeed working on s3

**Comment by kylebarron** [comment]
See also https://github.com/apache/arrow-rs/issues/6285

**Comment by martindurant** [comment]
> We should test that it is indeed working on s3

I bet it doesn't on moto... I hear that minio have had it a while, though.

**Comment by kylebarron** [comment]
I mean we should manually test this on an actual S3 bucket.
